<?php


/**
 * This class adds structure of 'hr_categories' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/25/09 18:13:31
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class HrCategoriesMapBuilder implements OldMapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.HrCategoriesMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(HrCategoriesPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(HrCategoriesPeer::TABLE_NAME);
		$tMap->setPhpName('HrCategories');
		$tMap->setClassname('HrCategories');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('SLUG', 'Slug', 'VARCHAR', false, 255);

		$tMap->addColumn('TREE_LEFT', 'TreeLeft', 'INTEGER', true, null);

		$tMap->addColumn('TREE_RIGHT', 'TreeRight', 'INTEGER', true, null);

		$tMap->addColumn('TREE_PARENT', 'TreeParent', 'INTEGER', false, null);

		$tMap->addColumn('TOPIC_ID', 'TopicId', 'INTEGER', false, null);

		$tMap->addColumn('TITLE_EN', 'TitleEn', 'VARCHAR', false, 255);

		$tMap->addColumn('TITLE_FR', 'TitleFr', 'VARCHAR', false, 255);

		$tMap->addColumn('DESCRIPTION_EN', 'DescriptionEn', 'LONGVARCHAR', false, null);

		$tMap->addColumn('DESCRIPTION_FR', 'DescriptionFr', 'LONGVARCHAR', false, null);

		$tMap->addColumn('IS_PUBLISHED', 'IsPublished', 'BOOLEAN', true, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // HrCategoriesMapBuilder
