<?php


/**
 * This class adds structure of 'hr_resources' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 01/06/10 20:10:01
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class HrResourcesMapBuilder implements OldMapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.HrResourcesMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(HrResourcesPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(HrResourcesPeer::TABLE_NAME);
		$tMap->setPhpName('HrResources');
		$tMap->setClassname('HrResources');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('EN', 'En', 'BOOLEAN', true, null);

		$tMap->addColumn('FR', 'Fr', 'BOOLEAN', true, null);

		$tMap->addColumn('TITLE_EN', 'TitleEn', 'VARCHAR', false, 255);

		$tMap->addColumn('TITLE_FR', 'TitleFr', 'VARCHAR', false, 255);

		$tMap->addColumn('PUB_TYPE', 'PubType', 'VARCHAR', false, 12);

		$tMap->addColumn('PUB_FORMAT', 'PubFormat', 'VARCHAR', false, 12);

		$tMap->addColumn('KEYWORDS', 'Keywords', 'VARCHAR', false, 255);

		$tMap->addColumn('URL_EN', 'UrlEn', 'VARCHAR', false, 255);

		$tMap->addColumn('URL_FR', 'UrlFr', 'VARCHAR', false, 255);

		$tMap->addColumn('ORGANIZATION_EN', 'OrganizationEn', 'VARCHAR', false, 255);

		$tMap->addColumn('ORGANIZATION_FR', 'OrganizationFr', 'VARCHAR', false, 255);

		$tMap->addColumn('DESCRIPTION_EN', 'DescriptionEn', 'LONGVARCHAR', false, null);

		$tMap->addColumn('DESCRIPTION_FR', 'DescriptionFr', 'LONGVARCHAR', false, null);

		$tMap->addColumn('AUTHOR', 'Author', 'VARCHAR', false, 255);

		$tMap->addColumn('PUBLISHER', 'Publisher', 'VARCHAR', false, 255);

		$tMap->addColumn('PUB_DATE', 'PubDate', 'TIMESTAMP', false, null);

		$tMap->addColumn('PUB_PLACE', 'PubPlace', 'VARCHAR', false, 255);

		$tMap->addColumn('COUNTRY', 'Country', 'VARCHAR', false, 2);

		$tMap->addColumn('SERIES', 'Series', 'VARCHAR', false, 255);

		$tMap->addColumn('ISBN', 'Isbn', 'VARCHAR', false, 50);

		$tMap->addColumn('THUMBNAIL_EN', 'ThumbnailEn', 'VARCHAR', false, 255);

		$tMap->addColumn('THUMBNAIL_FR', 'ThumbnailFr', 'VARCHAR', false, 255);

		$tMap->addColumn('FIRST_NAME', 'FirstName', 'VARCHAR', false, 255);

		$tMap->addColumn('LAST_NAME', 'LastName', 'VARCHAR', false, 255);

		$tMap->addColumn('EMAIL', 'Email', 'VARCHAR', false, 255);

		$tMap->addColumn('PHONE', 'Phone', 'VARCHAR', false, 255);

		$tMap->addColumn('DATE_SUBMITTED', 'DateSubmitted', 'TIMESTAMP', false, null);

		$tMap->addColumn('APPROVED', 'Approved', 'BOOLEAN', true, null);

		$tMap->addColumn('CLICKS', 'Clicks', 'INTEGER', false, null);

		$tMap->addColumn('NOTES', 'Notes', 'LONGVARCHAR', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // HrResourcesMapBuilder
