<?php

/**
 * Base static class for performing query and update operations on the 'hr_resources' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 01/06/10 20:10:01
 *
 * @package    lib.model.om
 */
abstract class BaseHrResourcesPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'hr_resources';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.HrResources';

	/** The total number of columns. */
	const NUM_COLUMNS = 33;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'hr_resources.ID';

	/** the column name for the EN field */
	const EN = 'hr_resources.EN';

	/** the column name for the FR field */
	const FR = 'hr_resources.FR';

	/** the column name for the TITLE_EN field */
	const TITLE_EN = 'hr_resources.TITLE_EN';

	/** the column name for the TITLE_FR field */
	const TITLE_FR = 'hr_resources.TITLE_FR';

	/** the column name for the PUB_TYPE field */
	const PUB_TYPE = 'hr_resources.PUB_TYPE';

	/** the column name for the PUB_FORMAT field */
	const PUB_FORMAT = 'hr_resources.PUB_FORMAT';

	/** the column name for the KEYWORDS field */
	const KEYWORDS = 'hr_resources.KEYWORDS';

	/** the column name for the URL_EN field */
	const URL_EN = 'hr_resources.URL_EN';

	/** the column name for the URL_FR field */
	const URL_FR = 'hr_resources.URL_FR';

	/** the column name for the ORGANIZATION_EN field */
	const ORGANIZATION_EN = 'hr_resources.ORGANIZATION_EN';

	/** the column name for the ORGANIZATION_FR field */
	const ORGANIZATION_FR = 'hr_resources.ORGANIZATION_FR';

	/** the column name for the DESCRIPTION_EN field */
	const DESCRIPTION_EN = 'hr_resources.DESCRIPTION_EN';

	/** the column name for the DESCRIPTION_FR field */
	const DESCRIPTION_FR = 'hr_resources.DESCRIPTION_FR';

	/** the column name for the AUTHOR field */
	const AUTHOR = 'hr_resources.AUTHOR';

	/** the column name for the PUBLISHER field */
	const PUBLISHER = 'hr_resources.PUBLISHER';

	/** the column name for the PUB_DATE field */
	const PUB_DATE = 'hr_resources.PUB_DATE';

	/** the column name for the PUB_PLACE field */
	const PUB_PLACE = 'hr_resources.PUB_PLACE';

	/** the column name for the COUNTRY field */
	const COUNTRY = 'hr_resources.COUNTRY';

	/** the column name for the SERIES field */
	const SERIES = 'hr_resources.SERIES';

	/** the column name for the ISBN field */
	const ISBN = 'hr_resources.ISBN';

	/** the column name for the THUMBNAIL_EN field */
	const THUMBNAIL_EN = 'hr_resources.THUMBNAIL_EN';

	/** the column name for the THUMBNAIL_FR field */
	const THUMBNAIL_FR = 'hr_resources.THUMBNAIL_FR';

	/** the column name for the FIRST_NAME field */
	const FIRST_NAME = 'hr_resources.FIRST_NAME';

	/** the column name for the LAST_NAME field */
	const LAST_NAME = 'hr_resources.LAST_NAME';

	/** the column name for the EMAIL field */
	const EMAIL = 'hr_resources.EMAIL';

	/** the column name for the PHONE field */
	const PHONE = 'hr_resources.PHONE';

	/** the column name for the DATE_SUBMITTED field */
	const DATE_SUBMITTED = 'hr_resources.DATE_SUBMITTED';

	/** the column name for the APPROVED field */
	const APPROVED = 'hr_resources.APPROVED';

	/** the column name for the CLICKS field */
	const CLICKS = 'hr_resources.CLICKS';

	/** the column name for the NOTES field */
	const NOTES = 'hr_resources.NOTES';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'hr_resources.CREATED_AT';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'hr_resources.UPDATED_AT';

	/**
	 * An identiy map to hold any loaded instances of HrResources objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array HrResources[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'En', 'Fr', 'TitleEn', 'TitleFr', 'PubType', 'PubFormat', 'Keywords', 'UrlEn', 'UrlFr', 'OrganizationEn', 'OrganizationFr', 'DescriptionEn', 'DescriptionFr', 'Author', 'Publisher', 'PubDate', 'PubPlace', 'Country', 'Series', 'Isbn', 'ThumbnailEn', 'ThumbnailFr', 'FirstName', 'LastName', 'Email', 'Phone', 'DateSubmitted', 'Approved', 'Clicks', 'Notes', 'CreatedAt', 'UpdatedAt', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'en', 'fr', 'titleEn', 'titleFr', 'pubType', 'pubFormat', 'keywords', 'urlEn', 'urlFr', 'organizationEn', 'organizationFr', 'descriptionEn', 'descriptionFr', 'author', 'publisher', 'pubDate', 'pubPlace', 'country', 'series', 'isbn', 'thumbnailEn', 'thumbnailFr', 'firstName', 'lastName', 'email', 'phone', 'dateSubmitted', 'approved', 'clicks', 'notes', 'createdAt', 'updatedAt', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::EN, self::FR, self::TITLE_EN, self::TITLE_FR, self::PUB_TYPE, self::PUB_FORMAT, self::KEYWORDS, self::URL_EN, self::URL_FR, self::ORGANIZATION_EN, self::ORGANIZATION_FR, self::DESCRIPTION_EN, self::DESCRIPTION_FR, self::AUTHOR, self::PUBLISHER, self::PUB_DATE, self::PUB_PLACE, self::COUNTRY, self::SERIES, self::ISBN, self::THUMBNAIL_EN, self::THUMBNAIL_FR, self::FIRST_NAME, self::LAST_NAME, self::EMAIL, self::PHONE, self::DATE_SUBMITTED, self::APPROVED, self::CLICKS, self::NOTES, self::CREATED_AT, self::UPDATED_AT, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'en', 'fr', 'title_en', 'title_fr', 'pub_type', 'pub_format', 'keywords', 'url_en', 'url_fr', 'organization_en', 'organization_fr', 'description_en', 'description_fr', 'author', 'publisher', 'pub_date', 'pub_place', 'country', 'series', 'isbn', 'thumbnail_en', 'thumbnail_fr', 'first_name', 'last_name', 'email', 'phone', 'date_submitted', 'approved', 'clicks', 'notes', 'created_at', 'updated_at', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'En' => 1, 'Fr' => 2, 'TitleEn' => 3, 'TitleFr' => 4, 'PubType' => 5, 'PubFormat' => 6, 'Keywords' => 7, 'UrlEn' => 8, 'UrlFr' => 9, 'OrganizationEn' => 10, 'OrganizationFr' => 11, 'DescriptionEn' => 12, 'DescriptionFr' => 13, 'Author' => 14, 'Publisher' => 15, 'PubDate' => 16, 'PubPlace' => 17, 'Country' => 18, 'Series' => 19, 'Isbn' => 20, 'ThumbnailEn' => 21, 'ThumbnailFr' => 22, 'FirstName' => 23, 'LastName' => 24, 'Email' => 25, 'Phone' => 26, 'DateSubmitted' => 27, 'Approved' => 28, 'Clicks' => 29, 'Notes' => 30, 'CreatedAt' => 31, 'UpdatedAt' => 32, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'en' => 1, 'fr' => 2, 'titleEn' => 3, 'titleFr' => 4, 'pubType' => 5, 'pubFormat' => 6, 'keywords' => 7, 'urlEn' => 8, 'urlFr' => 9, 'organizationEn' => 10, 'organizationFr' => 11, 'descriptionEn' => 12, 'descriptionFr' => 13, 'author' => 14, 'publisher' => 15, 'pubDate' => 16, 'pubPlace' => 17, 'country' => 18, 'series' => 19, 'isbn' => 20, 'thumbnailEn' => 21, 'thumbnailFr' => 22, 'firstName' => 23, 'lastName' => 24, 'email' => 25, 'phone' => 26, 'dateSubmitted' => 27, 'approved' => 28, 'clicks' => 29, 'notes' => 30, 'createdAt' => 31, 'updatedAt' => 32, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::EN => 1, self::FR => 2, self::TITLE_EN => 3, self::TITLE_FR => 4, self::PUB_TYPE => 5, self::PUB_FORMAT => 6, self::KEYWORDS => 7, self::URL_EN => 8, self::URL_FR => 9, self::ORGANIZATION_EN => 10, self::ORGANIZATION_FR => 11, self::DESCRIPTION_EN => 12, self::DESCRIPTION_FR => 13, self::AUTHOR => 14, self::PUBLISHER => 15, self::PUB_DATE => 16, self::PUB_PLACE => 17, self::COUNTRY => 18, self::SERIES => 19, self::ISBN => 20, self::THUMBNAIL_EN => 21, self::THUMBNAIL_FR => 22, self::FIRST_NAME => 23, self::LAST_NAME => 24, self::EMAIL => 25, self::PHONE => 26, self::DATE_SUBMITTED => 27, self::APPROVED => 28, self::CLICKS => 29, self::NOTES => 30, self::CREATED_AT => 31, self::UPDATED_AT => 32, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'en' => 1, 'fr' => 2, 'title_en' => 3, 'title_fr' => 4, 'pub_type' => 5, 'pub_format' => 6, 'keywords' => 7, 'url_en' => 8, 'url_fr' => 9, 'organization_en' => 10, 'organization_fr' => 11, 'description_en' => 12, 'description_fr' => 13, 'author' => 14, 'publisher' => 15, 'pub_date' => 16, 'pub_place' => 17, 'country' => 18, 'series' => 19, 'isbn' => 20, 'thumbnail_en' => 21, 'thumbnail_fr' => 22, 'first_name' => 23, 'last_name' => 24, 'email' => 25, 'phone' => 26, 'date_submitted' => 27, 'approved' => 28, 'clicks' => 29, 'notes' => 30, 'created_at' => 31, 'updated_at' => 32, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new HrResourcesMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. HrResourcesPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(HrResourcesPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(HrResourcesPeer::ID);

		$criteria->addSelectColumn(HrResourcesPeer::EN);

		$criteria->addSelectColumn(HrResourcesPeer::FR);

		$criteria->addSelectColumn(HrResourcesPeer::TITLE_EN);

		$criteria->addSelectColumn(HrResourcesPeer::TITLE_FR);

		$criteria->addSelectColumn(HrResourcesPeer::PUB_TYPE);

		$criteria->addSelectColumn(HrResourcesPeer::PUB_FORMAT);

		$criteria->addSelectColumn(HrResourcesPeer::KEYWORDS);

		$criteria->addSelectColumn(HrResourcesPeer::URL_EN);

		$criteria->addSelectColumn(HrResourcesPeer::URL_FR);

		$criteria->addSelectColumn(HrResourcesPeer::ORGANIZATION_EN);

		$criteria->addSelectColumn(HrResourcesPeer::ORGANIZATION_FR);

		$criteria->addSelectColumn(HrResourcesPeer::DESCRIPTION_EN);

		$criteria->addSelectColumn(HrResourcesPeer::DESCRIPTION_FR);

		$criteria->addSelectColumn(HrResourcesPeer::AUTHOR);

		$criteria->addSelectColumn(HrResourcesPeer::PUBLISHER);

		$criteria->addSelectColumn(HrResourcesPeer::PUB_DATE);

		$criteria->addSelectColumn(HrResourcesPeer::PUB_PLACE);

		$criteria->addSelectColumn(HrResourcesPeer::COUNTRY);

		$criteria->addSelectColumn(HrResourcesPeer::SERIES);

		$criteria->addSelectColumn(HrResourcesPeer::ISBN);

		$criteria->addSelectColumn(HrResourcesPeer::THUMBNAIL_EN);

		$criteria->addSelectColumn(HrResourcesPeer::THUMBNAIL_FR);

		$criteria->addSelectColumn(HrResourcesPeer::FIRST_NAME);

		$criteria->addSelectColumn(HrResourcesPeer::LAST_NAME);

		$criteria->addSelectColumn(HrResourcesPeer::EMAIL);

		$criteria->addSelectColumn(HrResourcesPeer::PHONE);

		$criteria->addSelectColumn(HrResourcesPeer::DATE_SUBMITTED);

		$criteria->addSelectColumn(HrResourcesPeer::APPROVED);

		$criteria->addSelectColumn(HrResourcesPeer::CLICKS);

		$criteria->addSelectColumn(HrResourcesPeer::NOTES);

		$criteria->addSelectColumn(HrResourcesPeer::CREATED_AT);

		$criteria->addSelectColumn(HrResourcesPeer::UPDATED_AT);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(HrResourcesPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			HrResourcesPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(HrResourcesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseHrResourcesPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseHrResourcesPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     HrResources
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = HrResourcesPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return HrResourcesPeer::populateObjects(HrResourcesPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseHrResourcesPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseHrResourcesPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(HrResourcesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			HrResourcesPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      HrResources $value A HrResources object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(HrResources $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A HrResources object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof HrResources) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or HrResources object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     HrResources Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = HrResourcesPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = HrResourcesPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = HrResourcesPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				HrResourcesPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return HrResourcesPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a HrResources or Criteria object.
	 *
	 * @param      mixed $values Criteria or HrResources object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseHrResourcesPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseHrResourcesPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(HrResourcesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from HrResources object
		}

		if ($criteria->containsKey(HrResourcesPeer::ID) && $criteria->keyContainsValue(HrResourcesPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.HrResourcesPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseHrResourcesPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseHrResourcesPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a HrResources or Criteria object.
	 *
	 * @param      mixed $values Criteria or HrResources object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseHrResourcesPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseHrResourcesPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(HrResourcesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(HrResourcesPeer::ID);
			$selectCriteria->add(HrResourcesPeer::ID, $criteria->remove(HrResourcesPeer::ID), $comparison);

		} else { // $values is HrResources object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseHrResourcesPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseHrResourcesPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the hr_resources table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(HrResourcesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += HrResourcesPeer::doOnDeleteCascade(new Criteria(HrResourcesPeer::DATABASE_NAME), $con);
			$affectedRows += BasePeer::doDeleteAll(HrResourcesPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a HrResources or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or HrResources object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(HrResourcesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			HrResourcesPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof HrResources) {
			// invalidate the cache for this single object
			HrResourcesPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(HrResourcesPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				HrResourcesPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += HrResourcesPeer::doOnDeleteCascade($criteria, $con);
			
				// Because this db requires some delete cascade/set null emulation, we have to
				// clear the cached instance *after* the emulation has happened (since
				// instances get re-added by the select statement contained therein).
				if ($values instanceof Criteria) {
					HrResourcesPeer::clearInstancePool();
				} else { // it's a PK or object
					HrResourcesPeer::removeInstanceFromPool($values);
				}
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			// invalidate objects in HrResourceCategoriesRelationsPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			HrResourceCategoriesRelationsPeer::clearInstancePool();

			// invalidate objects in HrResourceKeywordsRelationsPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			HrResourceKeywordsRelationsPeer::clearInstancePool();

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * This is a method for emulating ON DELETE CASCADE for DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	protected static function doOnDeleteCascade(Criteria $criteria, PropelPDO $con)
	{
		// initialize var to track total num of affected rows
		$affectedRows = 0;

		// first find the objects that are implicated by the $criteria
		$objects = HrResourcesPeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {


			// delete related HrResourceCategoriesRelations objects
			$c = new Criteria(HrResourceCategoriesRelationsPeer::DATABASE_NAME);
			
			$c->add(HrResourceCategoriesRelationsPeer::HR_RESOURCES_ID, $obj->getId());
			$affectedRows += HrResourceCategoriesRelationsPeer::doDelete($c, $con);

			// delete related HrResourceKeywordsRelations objects
			$c = new Criteria(HrResourceKeywordsRelationsPeer::DATABASE_NAME);
			
			$c->add(HrResourceKeywordsRelationsPeer::HR_RESOURCES_ID, $obj->getId());
			$affectedRows += HrResourceKeywordsRelationsPeer::doDelete($c, $con);
		}
		return $affectedRows;
	}

	/**
	 * Validates all modified columns of given HrResources object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      HrResources $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(HrResources $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(HrResourcesPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(HrResourcesPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(HrResourcesPeer::DATABASE_NAME, HrResourcesPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = HrResourcesPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     HrResources
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = HrResourcesPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(HrResourcesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(HrResourcesPeer::DATABASE_NAME);
		$criteria->add(HrResourcesPeer::ID, $pk);

		$v = HrResourcesPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(HrResourcesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(HrResourcesPeer::DATABASE_NAME);
			$criteria->add(HrResourcesPeer::ID, $pks, Criteria::IN);
			$objs = HrResourcesPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseHrResourcesPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the HrResourcesPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the HrResourcesPeer class:
//
// Propel::getDatabaseMap(HrResourcesPeer::DATABASE_NAME)->addTableBuilder(HrResourcesPeer::TABLE_NAME, HrResourcesPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::setDatabaseMapClass('OldDatabaseMap');
Propel::getDatabaseMap(BaseHrResourcesPeer::DATABASE_NAME)->addTableBuilder(BaseHrResourcesPeer::TABLE_NAME, BaseHrResourcesPeer::getMapBuilder());

