<?php

/**
 * Base class that represents a row from the 'hr_categories' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/25/09 18:13:31
 *
 * @package    lib.model.om
 */
abstract class BaseHrCategories extends BaseObject  implements Persistent {


  const PEER = 'HrCategoriesPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        HrCategoriesPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the slug field.
	 * @var        string
	 */
	protected $slug;

	/**
	 * The value for the tree_left field.
	 * @var        int
	 */
	protected $tree_left;

	/**
	 * The value for the tree_right field.
	 * @var        int
	 */
	protected $tree_right;

	/**
	 * The value for the tree_parent field.
	 * @var        int
	 */
	protected $tree_parent;

	/**
	 * The value for the topic_id field.
	 * @var        int
	 */
	protected $topic_id;

	/**
	 * The value for the title_en field.
	 * @var        string
	 */
	protected $title_en;

	/**
	 * The value for the title_fr field.
	 * @var        string
	 */
	protected $title_fr;

	/**
	 * The value for the description_en field.
	 * @var        string
	 */
	protected $description_en;

	/**
	 * The value for the description_fr field.
	 * @var        string
	 */
	protected $description_fr;

	/**
	 * The value for the is_published field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_published;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        array HrResourceCategoriesRelations[] Collection to store aggregation of HrResourceCategoriesRelations objects.
	 */
	protected $collHrResourceCategoriesRelationss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collHrResourceCategoriesRelationss.
	 */
	private $lastHrResourceCategoriesRelationsCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseHrCategories object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->is_published = false;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [slug] column value.
	 * 
	 * @return     string
	 */
	public function getSlug()
	{
		return $this->slug;
	}

	/**
	 * Get the [tree_left] column value.
	 * 
	 * @return     int
	 */
	public function getTreeLeft()
	{
		return $this->tree_left;
	}

	/**
	 * Get the [tree_right] column value.
	 * 
	 * @return     int
	 */
	public function getTreeRight()
	{
		return $this->tree_right;
	}

	/**
	 * Get the [tree_parent] column value.
	 * 
	 * @return     int
	 */
	public function getTreeParent()
	{
		return $this->tree_parent;
	}

	/**
	 * Get the [topic_id] column value.
	 * 
	 * @return     int
	 */
	public function getTopicId()
	{
		return $this->topic_id;
	}

	/**
	 * Get the [title_en] column value.
	 * 
	 * @return     string
	 */
	public function getTitleEn()
	{
		return $this->title_en;
	}

	/**
	 * Get the [title_fr] column value.
	 * 
	 * @return     string
	 */
	public function getTitleFr()
	{
		return $this->title_fr;
	}

	/**
	 * Get the [description_en] column value.
	 * 
	 * @return     string
	 */
	public function getDescriptionEn()
	{
		return $this->description_en;
	}

	/**
	 * Get the [description_fr] column value.
	 * 
	 * @return     string
	 */
	public function getDescriptionFr()
	{
		return $this->description_fr;
	}

	/**
	 * Get the [is_published] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsPublished()
	{
		return $this->is_published;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     HrCategories The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = HrCategoriesPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [slug] column.
	 * 
	 * @param      string $v new value
	 * @return     HrCategories The current object (for fluent API support)
	 */
	public function setSlug($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->slug !== $v) {
			$this->slug = $v;
			$this->modifiedColumns[] = HrCategoriesPeer::SLUG;
		}

		return $this;
	} // setSlug()

	/**
	 * Set the value of [tree_left] column.
	 * 
	 * @param      int $v new value
	 * @return     HrCategories The current object (for fluent API support)
	 */
	public function setTreeLeft($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tree_left !== $v) {
			$this->tree_left = $v;
			$this->modifiedColumns[] = HrCategoriesPeer::TREE_LEFT;
		}

		return $this;
	} // setTreeLeft()

	/**
	 * Set the value of [tree_right] column.
	 * 
	 * @param      int $v new value
	 * @return     HrCategories The current object (for fluent API support)
	 */
	public function setTreeRight($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tree_right !== $v) {
			$this->tree_right = $v;
			$this->modifiedColumns[] = HrCategoriesPeer::TREE_RIGHT;
		}

		return $this;
	} // setTreeRight()

	/**
	 * Set the value of [tree_parent] column.
	 * 
	 * @param      int $v new value
	 * @return     HrCategories The current object (for fluent API support)
	 */
	public function setTreeParent($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tree_parent !== $v) {
			$this->tree_parent = $v;
			$this->modifiedColumns[] = HrCategoriesPeer::TREE_PARENT;
		}

		return $this;
	} // setTreeParent()

	/**
	 * Set the value of [topic_id] column.
	 * 
	 * @param      int $v new value
	 * @return     HrCategories The current object (for fluent API support)
	 */
	public function setTopicId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->topic_id !== $v) {
			$this->topic_id = $v;
			$this->modifiedColumns[] = HrCategoriesPeer::TOPIC_ID;
		}

		return $this;
	} // setTopicId()

	/**
	 * Set the value of [title_en] column.
	 * 
	 * @param      string $v new value
	 * @return     HrCategories The current object (for fluent API support)
	 */
	public function setTitleEn($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title_en !== $v) {
			$this->title_en = $v;
			$this->modifiedColumns[] = HrCategoriesPeer::TITLE_EN;
		}

		return $this;
	} // setTitleEn()

	/**
	 * Set the value of [title_fr] column.
	 * 
	 * @param      string $v new value
	 * @return     HrCategories The current object (for fluent API support)
	 */
	public function setTitleFr($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title_fr !== $v) {
			$this->title_fr = $v;
			$this->modifiedColumns[] = HrCategoriesPeer::TITLE_FR;
		}

		return $this;
	} // setTitleFr()

	/**
	 * Set the value of [description_en] column.
	 * 
	 * @param      string $v new value
	 * @return     HrCategories The current object (for fluent API support)
	 */
	public function setDescriptionEn($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description_en !== $v) {
			$this->description_en = $v;
			$this->modifiedColumns[] = HrCategoriesPeer::DESCRIPTION_EN;
		}

		return $this;
	} // setDescriptionEn()

	/**
	 * Set the value of [description_fr] column.
	 * 
	 * @param      string $v new value
	 * @return     HrCategories The current object (for fluent API support)
	 */
	public function setDescriptionFr($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description_fr !== $v) {
			$this->description_fr = $v;
			$this->modifiedColumns[] = HrCategoriesPeer::DESCRIPTION_FR;
		}

		return $this;
	} // setDescriptionFr()

	/**
	 * Set the value of [is_published] column.
	 * 
	 * @param      boolean $v new value
	 * @return     HrCategories The current object (for fluent API support)
	 */
	public function setIsPublished($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_published !== $v || $v === false) {
			$this->is_published = $v;
			$this->modifiedColumns[] = HrCategoriesPeer::IS_PUBLISHED;
		}

		return $this;
	} // setIsPublished()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     HrCategories The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = HrCategoriesPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     HrCategories The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = HrCategoriesPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(HrCategoriesPeer::IS_PUBLISHED))) {
				return false;
			}

			if ($this->is_published !== false) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->slug = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->tree_left = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->tree_right = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->tree_parent = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->topic_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->title_en = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->title_fr = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->description_en = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->description_fr = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->is_published = ($row[$startcol + 10] !== null) ? (boolean) $row[$startcol + 10] : null;
			$this->created_at = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->updated_at = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 13; // 13 = HrCategoriesPeer::NUM_COLUMNS - HrCategoriesPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating HrCategories object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(HrCategoriesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = HrCategoriesPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collHrResourceCategoriesRelationss = null;
			$this->lastHrResourceCategoriesRelationsCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseHrCategories:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(HrCategoriesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			HrCategoriesPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseHrCategories:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseHrCategories:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(HrCategoriesPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(HrCategoriesPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(HrCategoriesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseHrCategories:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			HrCategoriesPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = HrCategoriesPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = HrCategoriesPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += HrCategoriesPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collHrResourceCategoriesRelationss !== null) {
				foreach ($this->collHrResourceCategoriesRelationss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = HrCategoriesPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collHrResourceCategoriesRelationss !== null) {
					foreach ($this->collHrResourceCategoriesRelationss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = HrCategoriesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getSlug();
				break;
			case 2:
				return $this->getTreeLeft();
				break;
			case 3:
				return $this->getTreeRight();
				break;
			case 4:
				return $this->getTreeParent();
				break;
			case 5:
				return $this->getTopicId();
				break;
			case 6:
				return $this->getTitleEn();
				break;
			case 7:
				return $this->getTitleFr();
				break;
			case 8:
				return $this->getDescriptionEn();
				break;
			case 9:
				return $this->getDescriptionFr();
				break;
			case 10:
				return $this->getIsPublished();
				break;
			case 11:
				return $this->getCreatedAt();
				break;
			case 12:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = HrCategoriesPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getSlug(),
			$keys[2] => $this->getTreeLeft(),
			$keys[3] => $this->getTreeRight(),
			$keys[4] => $this->getTreeParent(),
			$keys[5] => $this->getTopicId(),
			$keys[6] => $this->getTitleEn(),
			$keys[7] => $this->getTitleFr(),
			$keys[8] => $this->getDescriptionEn(),
			$keys[9] => $this->getDescriptionFr(),
			$keys[10] => $this->getIsPublished(),
			$keys[11] => $this->getCreatedAt(),
			$keys[12] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = HrCategoriesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setSlug($value);
				break;
			case 2:
				$this->setTreeLeft($value);
				break;
			case 3:
				$this->setTreeRight($value);
				break;
			case 4:
				$this->setTreeParent($value);
				break;
			case 5:
				$this->setTopicId($value);
				break;
			case 6:
				$this->setTitleEn($value);
				break;
			case 7:
				$this->setTitleFr($value);
				break;
			case 8:
				$this->setDescriptionEn($value);
				break;
			case 9:
				$this->setDescriptionFr($value);
				break;
			case 10:
				$this->setIsPublished($value);
				break;
			case 11:
				$this->setCreatedAt($value);
				break;
			case 12:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = HrCategoriesPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setSlug($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTreeLeft($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTreeRight($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTreeParent($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setTopicId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setTitleEn($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setTitleFr($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setDescriptionEn($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setDescriptionFr($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setIsPublished($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setCreatedAt($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setUpdatedAt($arr[$keys[12]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(HrCategoriesPeer::DATABASE_NAME);

		if ($this->isColumnModified(HrCategoriesPeer::ID)) $criteria->add(HrCategoriesPeer::ID, $this->id);
		if ($this->isColumnModified(HrCategoriesPeer::SLUG)) $criteria->add(HrCategoriesPeer::SLUG, $this->slug);
		if ($this->isColumnModified(HrCategoriesPeer::TREE_LEFT)) $criteria->add(HrCategoriesPeer::TREE_LEFT, $this->tree_left);
		if ($this->isColumnModified(HrCategoriesPeer::TREE_RIGHT)) $criteria->add(HrCategoriesPeer::TREE_RIGHT, $this->tree_right);
		if ($this->isColumnModified(HrCategoriesPeer::TREE_PARENT)) $criteria->add(HrCategoriesPeer::TREE_PARENT, $this->tree_parent);
		if ($this->isColumnModified(HrCategoriesPeer::TOPIC_ID)) $criteria->add(HrCategoriesPeer::TOPIC_ID, $this->topic_id);
		if ($this->isColumnModified(HrCategoriesPeer::TITLE_EN)) $criteria->add(HrCategoriesPeer::TITLE_EN, $this->title_en);
		if ($this->isColumnModified(HrCategoriesPeer::TITLE_FR)) $criteria->add(HrCategoriesPeer::TITLE_FR, $this->title_fr);
		if ($this->isColumnModified(HrCategoriesPeer::DESCRIPTION_EN)) $criteria->add(HrCategoriesPeer::DESCRIPTION_EN, $this->description_en);
		if ($this->isColumnModified(HrCategoriesPeer::DESCRIPTION_FR)) $criteria->add(HrCategoriesPeer::DESCRIPTION_FR, $this->description_fr);
		if ($this->isColumnModified(HrCategoriesPeer::IS_PUBLISHED)) $criteria->add(HrCategoriesPeer::IS_PUBLISHED, $this->is_published);
		if ($this->isColumnModified(HrCategoriesPeer::CREATED_AT)) $criteria->add(HrCategoriesPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(HrCategoriesPeer::UPDATED_AT)) $criteria->add(HrCategoriesPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(HrCategoriesPeer::DATABASE_NAME);

		$criteria->add(HrCategoriesPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of HrCategories (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setSlug($this->slug);

		$copyObj->setTreeLeft($this->tree_left);

		$copyObj->setTreeRight($this->tree_right);

		$copyObj->setTreeParent($this->tree_parent);

		$copyObj->setTopicId($this->topic_id);

		$copyObj->setTitleEn($this->title_en);

		$copyObj->setTitleFr($this->title_fr);

		$copyObj->setDescriptionEn($this->description_en);

		$copyObj->setDescriptionFr($this->description_fr);

		$copyObj->setIsPublished($this->is_published);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getHrResourceCategoriesRelationss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addHrResourceCategoriesRelations($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     HrCategories Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     HrCategoriesPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new HrCategoriesPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collHrResourceCategoriesRelationss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addHrResourceCategoriesRelationss()
	 */
	public function clearHrResourceCategoriesRelationss()
	{
		$this->collHrResourceCategoriesRelationss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collHrResourceCategoriesRelationss collection (array).
	 *
	 * By default this just sets the collHrResourceCategoriesRelationss collection to an empty array (like clearcollHrResourceCategoriesRelationss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initHrResourceCategoriesRelationss()
	{
		$this->collHrResourceCategoriesRelationss = array();
	}

	/**
	 * Gets an array of HrResourceCategoriesRelations objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this HrCategories has previously been saved, it will retrieve
	 * related HrResourceCategoriesRelationss from storage. If this HrCategories is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array HrResourceCategoriesRelations[]
	 * @throws     PropelException
	 */
	public function getHrResourceCategoriesRelationss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(HrCategoriesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collHrResourceCategoriesRelationss === null) {
			if ($this->isNew()) {
			   $this->collHrResourceCategoriesRelationss = array();
			} else {

				$criteria->add(HrResourceCategoriesRelationsPeer::HR_CATEGORIES_ID, $this->id);

				HrResourceCategoriesRelationsPeer::addSelectColumns($criteria);
				$this->collHrResourceCategoriesRelationss = HrResourceCategoriesRelationsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(HrResourceCategoriesRelationsPeer::HR_CATEGORIES_ID, $this->id);

				HrResourceCategoriesRelationsPeer::addSelectColumns($criteria);
				if (!isset($this->lastHrResourceCategoriesRelationsCriteria) || !$this->lastHrResourceCategoriesRelationsCriteria->equals($criteria)) {
					$this->collHrResourceCategoriesRelationss = HrResourceCategoriesRelationsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastHrResourceCategoriesRelationsCriteria = $criteria;
		return $this->collHrResourceCategoriesRelationss;
	}

	/**
	 * Returns the number of related HrResourceCategoriesRelations objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related HrResourceCategoriesRelations objects.
	 * @throws     PropelException
	 */
	public function countHrResourceCategoriesRelationss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(HrCategoriesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collHrResourceCategoriesRelationss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(HrResourceCategoriesRelationsPeer::HR_CATEGORIES_ID, $this->id);

				$count = HrResourceCategoriesRelationsPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(HrResourceCategoriesRelationsPeer::HR_CATEGORIES_ID, $this->id);

				if (!isset($this->lastHrResourceCategoriesRelationsCriteria) || !$this->lastHrResourceCategoriesRelationsCriteria->equals($criteria)) {
					$count = HrResourceCategoriesRelationsPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collHrResourceCategoriesRelationss);
				}
			} else {
				$count = count($this->collHrResourceCategoriesRelationss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a HrResourceCategoriesRelations object to this object
	 * through the HrResourceCategoriesRelations foreign key attribute.
	 *
	 * @param      HrResourceCategoriesRelations $l HrResourceCategoriesRelations
	 * @return     void
	 * @throws     PropelException
	 */
	public function addHrResourceCategoriesRelations(HrResourceCategoriesRelations $l)
	{
		if ($this->collHrResourceCategoriesRelationss === null) {
			$this->initHrResourceCategoriesRelationss();
		}
		if (!in_array($l, $this->collHrResourceCategoriesRelationss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collHrResourceCategoriesRelationss, $l);
			$l->setHrCategories($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this HrCategories is new, it will return
	 * an empty collection; or if this HrCategories has previously
	 * been saved, it will retrieve related HrResourceCategoriesRelationss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in HrCategories.
	 */
	public function getHrResourceCategoriesRelationssJoinHrResources($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(HrCategoriesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collHrResourceCategoriesRelationss === null) {
			if ($this->isNew()) {
				$this->collHrResourceCategoriesRelationss = array();
			} else {

				$criteria->add(HrResourceCategoriesRelationsPeer::HR_CATEGORIES_ID, $this->id);

				$this->collHrResourceCategoriesRelationss = HrResourceCategoriesRelationsPeer::doSelectJoinHrResources($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(HrResourceCategoriesRelationsPeer::HR_CATEGORIES_ID, $this->id);

			if (!isset($this->lastHrResourceCategoriesRelationsCriteria) || !$this->lastHrResourceCategoriesRelationsCriteria->equals($criteria)) {
				$this->collHrResourceCategoriesRelationss = HrResourceCategoriesRelationsPeer::doSelectJoinHrResources($criteria, $con, $join_behavior);
			}
		}
		$this->lastHrResourceCategoriesRelationsCriteria = $criteria;

		return $this->collHrResourceCategoriesRelationss;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collHrResourceCategoriesRelationss) {
				foreach ((array) $this->collHrResourceCategoriesRelationss as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collHrResourceCategoriesRelationss = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseHrCategories:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseHrCategories::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseHrCategories
