# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:

        
  sfSimpleCMS:
    default_text:           '[text here](add)'   # Default text for page editable parts
    routes_register:        on                  # Use the plugin's routes
    rich_editing:           on                 # Use TinyMCE for rich text editing
    tinymce_options:        'language : "en", theme : "advanced", width : "100%" ,height : "500", file_browser_callback:"sfAssetsLibrary.fileBrowserCallBack", plugins : "paste,table,advimage,advlink,media", paste_create_paragraphs : false, paste_create_linebreaks : false, paste_use_dialog : true, paste_auto_cleanup_on_paste : true, paste_convert_middot_lists : false, paste_unindented_list_class : "unindentedList", paste_convert_headers_to_strong : true, paste_insert_word_content_callback : "convertWord",	theme_advanced_buttons1_add : "formatselect,styleselect,", theme_advanced_buttons3_add: "separator,cut,copy,paste,pasteword,media", theme_advanced_blockformats : "p,div,h1,h2,h3,h4,h5,h6,blockquote,dt,dd,code,samp", theme_advanced_styles : "none = ; blockquote = blockquote; Highlight Block = highlightBlock rounded; Footnote = footnote; resourceManager = resourceManager; brownTableLines = brownTableLines; wpBrownTable = wpBrownTable", content_css : "/css/editor.css"'   # Additional TinyMCE initialization options
    default_page:           home                # Slug (=path) of the default root page
    use_bundled_layout:     false                # Use the layout bundled with the plugin (allows native display of navigation menu and breadcrumb)
    use_bundled_stylesheet: false                # Use the stylesheet bundled with the plugin (only makes sens if you use the bundled layout, too)
    home_link:              BusGurus             # What is displayed on the top right corner of the pages (can be HTML code)
    tagline:                Where the best minds in the indusrty gather [name it](you)
    footer_message:         www.buscouncil.ca
    max_pages_in_list:      5                   # Maximum number of links displayed in an internal list of links
    use_l10n:               true                # Enable multiple versions for a single page
    escaping_strategy:      ESC_RAW             # How content entered in the CMS interface must be escaped. Leave at ESC_RAW for no escaping
    localizations:          [en,fr]             # If l10n is enabled, list of cultures in which pages are available
    default_culture:        en                  # If l10n is not enabled, default culture for pages
    editor_credential:                          # Name of the credential required for page editing (leave blank for free editing)
    publisher_credential:                       # Name of the credential required for page publishing (leave blank for free publishing)
    templates:                                  # Available templates
      simplePage:           Simple Page
      hrOnboardPage:        Hr Onboard  Page
      hrOnboardHomePage:        Hr Onboard Home Page     
      workforcePage:        Workforce Page
      roiPage:              ROI Page
      nosPage:              NOS Page
      wheelPage:            Wheel Page                  
      toolsBasePage:        Tools Base Page
      simplePageWhiteLinks: Simple Page White Links
      home:                 Home                #   the value is the name under which the template is presented in lists
    slot_types:                                 # Available slot types
      Text:           Simple text
      RichText:       Rich text
      Php:            PHP code
      Image:          Image
      Modular:        List of partials/components

