<?php


/**
 * This class defines the structure of the 'sf_simple_cms_page' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 12/18/18 19:29:16
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfSimpleCMSPlugin.lib.model.map
 */
class sfSimpleCMSPageTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfSimpleCMSPlugin.lib.model.map.sfSimpleCMSPageTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sf_simple_cms_page');
		$this->setPhpName('sfSimpleCMSPage');
		$this->setClassname('sfSimpleCMSPage');
		$this->setPackage('plugins.sfSimpleCMSPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('SLUG', 'Slug', 'VARCHAR', false, 255, null);
		$this->addColumn('TREE_LEFT', 'TreeLeft', 'INTEGER', true, null, null);
		$this->addColumn('TREE_RIGHT', 'TreeRight', 'INTEGER', true, null, null);
		$this->addForeignKey('TREE_PARENT', 'TreeParent', 'INTEGER', 'sf_simple_cms_page', 'ID', false, null, null);
		$this->addColumn('TOPIC_ID', 'TopicId', 'INTEGER', false, null, null);
		$this->addColumn('TEMPLATE', 'Template', 'VARCHAR', false, 100, null);
		$this->addColumn('IS_PUBLISHED', 'IsPublished', 'BOOLEAN', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('sfSimpleCMSPageRelatedByTreeParent', 'sfSimpleCMSPage', RelationMap::MANY_TO_ONE, array('tree_parent' => 'id', ), 'CASCADE', null);
    $this->addRelation('sfSimpleCMSPageRelatedByTreeParent', 'sfSimpleCMSPage', RelationMap::ONE_TO_MANY, array('id' => 'tree_parent', ), 'CASCADE', null);
    $this->addRelation('sfSimpleCMSSlot', 'sfSimpleCMSSlot', RelationMap::ONE_TO_MANY, array('id' => 'page_id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // sfSimpleCMSPageTableMap
