<?php


/**
 * This class adds structure of 'sf_simple_cms_slot' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 08/25/09 14:17:12
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfSimpleCMSPlugin.lib.model.map
 */
class sfSimpleCMSSlotMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfSimpleCMSPlugin.lib.model.map.sfSimpleCMSSlotMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(sfSimpleCMSSlotPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(sfSimpleCMSSlotPeer::TABLE_NAME);
		$tMap->setPhpName('sfSimpleCMSSlot');
		$tMap->setClassname('sfSimpleCMSSlot');

		$tMap->setUseIdGenerator(false);

		$tMap->addForeignPrimaryKey('PAGE_ID', 'PageId', 'INTEGER' , 'sf_simple_cms_page', 'ID', true, null);

		$tMap->addPrimaryKey('CULTURE', 'Culture', 'VARCHAR', true, 7);

		$tMap->addPrimaryKey('NAME', 'Name', 'VARCHAR', true, 100);

		$tMap->addColumn('TYPE', 'Type', 'VARCHAR', true, 100);

		$tMap->addColumn('VALUE', 'Value', 'LONGVARCHAR', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // sfSimpleCMSSlotMapBuilder
