default:
  stylesheets:    [main.css,admin.css,smoothness/jquery-ui-1.7.1.custom.css]
  javascripts:    [jquery-1.3.2.min.js, jquery-ui-1.7.1.custom.min.js]
  has_layout:     on
  layout:         admin