<?php

/**
 * Base class that represents a row from the 'sf_simple_cms_page' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 08/25/09 14:17:11
 *
 * @package    plugins.sfSimpleCMSPlugin.lib.model.om
 */
abstract class BasesfSimpleCMSPage extends BaseObject  implements Persistent {


  const PEER = 'sfSimpleCMSPagePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        sfSimpleCMSPagePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the slug field.
	 * @var        string
	 */
	protected $slug;

	/**
	 * The value for the tree_left field.
	 * @var        int
	 */
	protected $tree_left;

	/**
	 * The value for the tree_right field.
	 * @var        int
	 */
	protected $tree_right;

	/**
	 * The value for the tree_parent field.
	 * @var        int
	 */
	protected $tree_parent;

	/**
	 * The value for the topic_id field.
	 * @var        int
	 */
	protected $topic_id;

	/**
	 * The value for the template field.
	 * @var        string
	 */
	protected $template;

	/**
	 * The value for the is_published field.
	 * @var        boolean
	 */
	protected $is_published;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        sfSimpleCMSPage
	 */
	protected $asfSimpleCMSPageRelatedByTreeParent;

	/**
	 * @var        array sfSimpleCMSPage[] Collection to store aggregation of sfSimpleCMSPage objects.
	 */
	protected $collsfSimpleCMSPagesRelatedByTreeParent;

	/**
	 * @var        Criteria The criteria used to select the current contents of collsfSimpleCMSPagesRelatedByTreeParent.
	 */
	private $lastsfSimpleCMSPageRelatedByTreeParentCriteria = null;

	/**
	 * @var        array sfSimpleCMSSlot[] Collection to store aggregation of sfSimpleCMSSlot objects.
	 */
	protected $collsfSimpleCMSSlots;

	/**
	 * @var        Criteria The criteria used to select the current contents of collsfSimpleCMSSlots.
	 */
	private $lastsfSimpleCMSSlotCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BasesfSimpleCMSPage object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [slug] column value.
	 * 
	 * @return     string
	 */
	public function getSlug()
	{
		return $this->slug;
	}

	/**
	 * Get the [tree_left] column value.
	 * 
	 * @return     int
	 */
	public function getTreeLeft()
	{
		return $this->tree_left;
	}

	/**
	 * Get the [tree_right] column value.
	 * 
	 * @return     int
	 */
	public function getTreeRight()
	{
		return $this->tree_right;
	}

	/**
	 * Get the [tree_parent] column value.
	 * 
	 * @return     int
	 */
	public function getTreeParent()
	{
		return $this->tree_parent;
	}

	/**
	 * Get the [topic_id] column value.
	 * 
	 * @return     int
	 */
	public function getTopicId()
	{
		return $this->topic_id;
	}

	/**
	 * Get the [template] column value.
	 * 
	 * @return     string
	 */
	public function getTemplate()
	{
		return $this->template;
	}

	/**
	 * Get the [is_published] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsPublished()
	{
		return $this->is_published;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfSimpleCMSPage The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = sfSimpleCMSPagePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [slug] column.
	 * 
	 * @param      string $v new value
	 * @return     sfSimpleCMSPage The current object (for fluent API support)
	 */
	public function setSlug($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->slug !== $v) {
			$this->slug = $v;
			$this->modifiedColumns[] = sfSimpleCMSPagePeer::SLUG;
		}

		return $this;
	} // setSlug()

	/**
	 * Set the value of [tree_left] column.
	 * 
	 * @param      int $v new value
	 * @return     sfSimpleCMSPage The current object (for fluent API support)
	 */
	public function setTreeLeft($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tree_left !== $v) {
			$this->tree_left = $v;
			$this->modifiedColumns[] = sfSimpleCMSPagePeer::TREE_LEFT;
		}

		return $this;
	} // setTreeLeft()

	/**
	 * Set the value of [tree_right] column.
	 * 
	 * @param      int $v new value
	 * @return     sfSimpleCMSPage The current object (for fluent API support)
	 */
	public function setTreeRight($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tree_right !== $v) {
			$this->tree_right = $v;
			$this->modifiedColumns[] = sfSimpleCMSPagePeer::TREE_RIGHT;
		}

		return $this;
	} // setTreeRight()

	/**
	 * Set the value of [tree_parent] column.
	 * 
	 * @param      int $v new value
	 * @return     sfSimpleCMSPage The current object (for fluent API support)
	 */
	public function setTreeParent($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tree_parent !== $v) {
			$this->tree_parent = $v;
			$this->modifiedColumns[] = sfSimpleCMSPagePeer::TREE_PARENT;
		}

		if ($this->asfSimpleCMSPageRelatedByTreeParent !== null && $this->asfSimpleCMSPageRelatedByTreeParent->getId() !== $v) {
			$this->asfSimpleCMSPageRelatedByTreeParent = null;
		}

		return $this;
	} // setTreeParent()

	/**
	 * Set the value of [topic_id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfSimpleCMSPage The current object (for fluent API support)
	 */
	public function setTopicId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->topic_id !== $v) {
			$this->topic_id = $v;
			$this->modifiedColumns[] = sfSimpleCMSPagePeer::TOPIC_ID;
		}

		return $this;
	} // setTopicId()

	/**
	 * Set the value of [template] column.
	 * 
	 * @param      string $v new value
	 * @return     sfSimpleCMSPage The current object (for fluent API support)
	 */
	public function setTemplate($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->template !== $v) {
			$this->template = $v;
			$this->modifiedColumns[] = sfSimpleCMSPagePeer::TEMPLATE;
		}

		return $this;
	} // setTemplate()

	/**
	 * Set the value of [is_published] column.
	 * 
	 * @param      boolean $v new value
	 * @return     sfSimpleCMSPage The current object (for fluent API support)
	 */
	public function setIsPublished($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_published !== $v) {
			$this->is_published = $v;
			$this->modifiedColumns[] = sfSimpleCMSPagePeer::IS_PUBLISHED;
		}

		return $this;
	} // setIsPublished()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     sfSimpleCMSPage The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = sfSimpleCMSPagePeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     sfSimpleCMSPage The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = sfSimpleCMSPagePeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->slug = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->tree_left = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->tree_right = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->tree_parent = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->topic_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->template = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->is_published = ($row[$startcol + 7] !== null) ? (boolean) $row[$startcol + 7] : null;
			$this->created_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->updated_at = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = sfSimpleCMSPagePeer::NUM_COLUMNS - sfSimpleCMSPagePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating sfSimpleCMSPage object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->asfSimpleCMSPageRelatedByTreeParent !== null && $this->tree_parent !== $this->asfSimpleCMSPageRelatedByTreeParent->getId()) {
			$this->asfSimpleCMSPageRelatedByTreeParent = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfSimpleCMSPagePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = sfSimpleCMSPagePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->asfSimpleCMSPageRelatedByTreeParent = null;
			$this->collsfSimpleCMSPagesRelatedByTreeParent = null;
			$this->lastsfSimpleCMSPageRelatedByTreeParentCriteria = null;

			$this->collsfSimpleCMSSlots = null;
			$this->lastsfSimpleCMSSlotCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasesfSimpleCMSPage:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfSimpleCMSPagePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			sfSimpleCMSPagePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BasesfSimpleCMSPage:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasesfSimpleCMSPage:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(sfSimpleCMSPagePeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(sfSimpleCMSPagePeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfSimpleCMSPagePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BasesfSimpleCMSPage:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			sfSimpleCMSPagePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfSimpleCMSPageRelatedByTreeParent !== null) {
				if ($this->asfSimpleCMSPageRelatedByTreeParent->isModified() || $this->asfSimpleCMSPageRelatedByTreeParent->isNew()) {
					$affectedRows += $this->asfSimpleCMSPageRelatedByTreeParent->save($con);
				}
				$this->setsfSimpleCMSPageRelatedByTreeParent($this->asfSimpleCMSPageRelatedByTreeParent);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = sfSimpleCMSPagePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = sfSimpleCMSPagePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += sfSimpleCMSPagePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collsfSimpleCMSPagesRelatedByTreeParent !== null) {
				foreach ($this->collsfSimpleCMSPagesRelatedByTreeParent as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collsfSimpleCMSSlots !== null) {
				foreach ($this->collsfSimpleCMSSlots as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfSimpleCMSPageRelatedByTreeParent !== null) {
				if (!$this->asfSimpleCMSPageRelatedByTreeParent->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfSimpleCMSPageRelatedByTreeParent->getValidationFailures());
				}
			}


			if (($retval = sfSimpleCMSPagePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collsfSimpleCMSPagesRelatedByTreeParent !== null) {
					foreach ($this->collsfSimpleCMSPagesRelatedByTreeParent as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collsfSimpleCMSSlots !== null) {
					foreach ($this->collsfSimpleCMSSlots as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = sfSimpleCMSPagePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getSlug();
				break;
			case 2:
				return $this->getTreeLeft();
				break;
			case 3:
				return $this->getTreeRight();
				break;
			case 4:
				return $this->getTreeParent();
				break;
			case 5:
				return $this->getTopicId();
				break;
			case 6:
				return $this->getTemplate();
				break;
			case 7:
				return $this->getIsPublished();
				break;
			case 8:
				return $this->getCreatedAt();
				break;
			case 9:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = sfSimpleCMSPagePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getSlug(),
			$keys[2] => $this->getTreeLeft(),
			$keys[3] => $this->getTreeRight(),
			$keys[4] => $this->getTreeParent(),
			$keys[5] => $this->getTopicId(),
			$keys[6] => $this->getTemplate(),
			$keys[7] => $this->getIsPublished(),
			$keys[8] => $this->getCreatedAt(),
			$keys[9] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = sfSimpleCMSPagePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setSlug($value);
				break;
			case 2:
				$this->setTreeLeft($value);
				break;
			case 3:
				$this->setTreeRight($value);
				break;
			case 4:
				$this->setTreeParent($value);
				break;
			case 5:
				$this->setTopicId($value);
				break;
			case 6:
				$this->setTemplate($value);
				break;
			case 7:
				$this->setIsPublished($value);
				break;
			case 8:
				$this->setCreatedAt($value);
				break;
			case 9:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = sfSimpleCMSPagePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setSlug($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTreeLeft($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTreeRight($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTreeParent($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setTopicId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setTemplate($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setIsPublished($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setCreatedAt($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUpdatedAt($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(sfSimpleCMSPagePeer::DATABASE_NAME);

		if ($this->isColumnModified(sfSimpleCMSPagePeer::ID)) $criteria->add(sfSimpleCMSPagePeer::ID, $this->id);
		if ($this->isColumnModified(sfSimpleCMSPagePeer::SLUG)) $criteria->add(sfSimpleCMSPagePeer::SLUG, $this->slug);
		if ($this->isColumnModified(sfSimpleCMSPagePeer::TREE_LEFT)) $criteria->add(sfSimpleCMSPagePeer::TREE_LEFT, $this->tree_left);
		if ($this->isColumnModified(sfSimpleCMSPagePeer::TREE_RIGHT)) $criteria->add(sfSimpleCMSPagePeer::TREE_RIGHT, $this->tree_right);
		if ($this->isColumnModified(sfSimpleCMSPagePeer::TREE_PARENT)) $criteria->add(sfSimpleCMSPagePeer::TREE_PARENT, $this->tree_parent);
		if ($this->isColumnModified(sfSimpleCMSPagePeer::TOPIC_ID)) $criteria->add(sfSimpleCMSPagePeer::TOPIC_ID, $this->topic_id);
		if ($this->isColumnModified(sfSimpleCMSPagePeer::TEMPLATE)) $criteria->add(sfSimpleCMSPagePeer::TEMPLATE, $this->template);
		if ($this->isColumnModified(sfSimpleCMSPagePeer::IS_PUBLISHED)) $criteria->add(sfSimpleCMSPagePeer::IS_PUBLISHED, $this->is_published);
		if ($this->isColumnModified(sfSimpleCMSPagePeer::CREATED_AT)) $criteria->add(sfSimpleCMSPagePeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(sfSimpleCMSPagePeer::UPDATED_AT)) $criteria->add(sfSimpleCMSPagePeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(sfSimpleCMSPagePeer::DATABASE_NAME);

		$criteria->add(sfSimpleCMSPagePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of sfSimpleCMSPage (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setSlug($this->slug);

		$copyObj->setTreeLeft($this->tree_left);

		$copyObj->setTreeRight($this->tree_right);

		$copyObj->setTreeParent($this->tree_parent);

		$copyObj->setTopicId($this->topic_id);

		$copyObj->setTemplate($this->template);

		$copyObj->setIsPublished($this->is_published);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getsfSimpleCMSPagesRelatedByTreeParent() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addsfSimpleCMSPageRelatedByTreeParent($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getsfSimpleCMSSlots() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addsfSimpleCMSSlot($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     sfSimpleCMSPage Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     sfSimpleCMSPagePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new sfSimpleCMSPagePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a sfSimpleCMSPage object.
	 *
	 * @param      sfSimpleCMSPage $v
	 * @return     sfSimpleCMSPage The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfSimpleCMSPageRelatedByTreeParent(sfSimpleCMSPage $v = null)
	{
		if ($v === null) {
			$this->setTreeParent(NULL);
		} else {
			$this->setTreeParent($v->getId());
		}

		$this->asfSimpleCMSPageRelatedByTreeParent = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfSimpleCMSPage object, it will not be re-added.
		if ($v !== null) {
			$v->addsfSimpleCMSPageRelatedByTreeParent($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfSimpleCMSPage object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfSimpleCMSPage The associated sfSimpleCMSPage object.
	 * @throws     PropelException
	 */
	public function getsfSimpleCMSPageRelatedByTreeParent(PropelPDO $con = null)
	{
		if ($this->asfSimpleCMSPageRelatedByTreeParent === null && ($this->tree_parent !== null)) {
			$c = new Criteria(sfSimpleCMSPagePeer::DATABASE_NAME);
			$c->add(sfSimpleCMSPagePeer::ID, $this->tree_parent);
			$this->asfSimpleCMSPageRelatedByTreeParent = sfSimpleCMSPagePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfSimpleCMSPageRelatedByTreeParent->addsfSimpleCMSPagesRelatedByTreeParent($this);
			 */
		}
		return $this->asfSimpleCMSPageRelatedByTreeParent;
	}

	/**
	 * Clears out the collsfSimpleCMSPagesRelatedByTreeParent collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addsfSimpleCMSPagesRelatedByTreeParent()
	 */
	public function clearsfSimpleCMSPagesRelatedByTreeParent()
	{
		$this->collsfSimpleCMSPagesRelatedByTreeParent = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collsfSimpleCMSPagesRelatedByTreeParent collection (array).
	 *
	 * By default this just sets the collsfSimpleCMSPagesRelatedByTreeParent collection to an empty array (like clearcollsfSimpleCMSPagesRelatedByTreeParent());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initsfSimpleCMSPagesRelatedByTreeParent()
	{
		$this->collsfSimpleCMSPagesRelatedByTreeParent = array();
	}

	/**
	 * Gets an array of sfSimpleCMSPage objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this sfSimpleCMSPage has previously been saved, it will retrieve
	 * related sfSimpleCMSPagesRelatedByTreeParent from storage. If this sfSimpleCMSPage is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array sfSimpleCMSPage[]
	 * @throws     PropelException
	 */
	public function getsfSimpleCMSPagesRelatedByTreeParent($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfSimpleCMSPagePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collsfSimpleCMSPagesRelatedByTreeParent === null) {
			if ($this->isNew()) {
			   $this->collsfSimpleCMSPagesRelatedByTreeParent = array();
			} else {

				$criteria->add(sfSimpleCMSPagePeer::TREE_PARENT, $this->id);

				sfSimpleCMSPagePeer::addSelectColumns($criteria);
				$this->collsfSimpleCMSPagesRelatedByTreeParent = sfSimpleCMSPagePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(sfSimpleCMSPagePeer::TREE_PARENT, $this->id);

				sfSimpleCMSPagePeer::addSelectColumns($criteria);
				if (!isset($this->lastsfSimpleCMSPageRelatedByTreeParentCriteria) || !$this->lastsfSimpleCMSPageRelatedByTreeParentCriteria->equals($criteria)) {
					$this->collsfSimpleCMSPagesRelatedByTreeParent = sfSimpleCMSPagePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastsfSimpleCMSPageRelatedByTreeParentCriteria = $criteria;
		return $this->collsfSimpleCMSPagesRelatedByTreeParent;
	}

	/**
	 * Returns the number of related sfSimpleCMSPage objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related sfSimpleCMSPage objects.
	 * @throws     PropelException
	 */
	public function countsfSimpleCMSPagesRelatedByTreeParent(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfSimpleCMSPagePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collsfSimpleCMSPagesRelatedByTreeParent === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(sfSimpleCMSPagePeer::TREE_PARENT, $this->id);

				$count = sfSimpleCMSPagePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(sfSimpleCMSPagePeer::TREE_PARENT, $this->id);

				if (!isset($this->lastsfSimpleCMSPageRelatedByTreeParentCriteria) || !$this->lastsfSimpleCMSPageRelatedByTreeParentCriteria->equals($criteria)) {
					$count = sfSimpleCMSPagePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collsfSimpleCMSPagesRelatedByTreeParent);
				}
			} else {
				$count = count($this->collsfSimpleCMSPagesRelatedByTreeParent);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a sfSimpleCMSPage object to this object
	 * through the sfSimpleCMSPage foreign key attribute.
	 *
	 * @param      sfSimpleCMSPage $l sfSimpleCMSPage
	 * @return     void
	 * @throws     PropelException
	 */
	public function addsfSimpleCMSPageRelatedByTreeParent(sfSimpleCMSPage $l)
	{
		if ($this->collsfSimpleCMSPagesRelatedByTreeParent === null) {
			$this->initsfSimpleCMSPagesRelatedByTreeParent();
		}
		if (!in_array($l, $this->collsfSimpleCMSPagesRelatedByTreeParent, true)) { // only add it if the **same** object is not already associated
			array_push($this->collsfSimpleCMSPagesRelatedByTreeParent, $l);
			$l->setsfSimpleCMSPageRelatedByTreeParent($this);
		}
	}

	/**
	 * Clears out the collsfSimpleCMSSlots collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addsfSimpleCMSSlots()
	 */
	public function clearsfSimpleCMSSlots()
	{
		$this->collsfSimpleCMSSlots = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collsfSimpleCMSSlots collection (array).
	 *
	 * By default this just sets the collsfSimpleCMSSlots collection to an empty array (like clearcollsfSimpleCMSSlots());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initsfSimpleCMSSlots()
	{
		$this->collsfSimpleCMSSlots = array();
	}

	/**
	 * Gets an array of sfSimpleCMSSlot objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this sfSimpleCMSPage has previously been saved, it will retrieve
	 * related sfSimpleCMSSlots from storage. If this sfSimpleCMSPage is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array sfSimpleCMSSlot[]
	 * @throws     PropelException
	 */
	public function getsfSimpleCMSSlots($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfSimpleCMSPagePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collsfSimpleCMSSlots === null) {
			if ($this->isNew()) {
			   $this->collsfSimpleCMSSlots = array();
			} else {

				$criteria->add(sfSimpleCMSSlotPeer::PAGE_ID, $this->id);

				sfSimpleCMSSlotPeer::addSelectColumns($criteria);
				$this->collsfSimpleCMSSlots = sfSimpleCMSSlotPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(sfSimpleCMSSlotPeer::PAGE_ID, $this->id);

				sfSimpleCMSSlotPeer::addSelectColumns($criteria);
				if (!isset($this->lastsfSimpleCMSSlotCriteria) || !$this->lastsfSimpleCMSSlotCriteria->equals($criteria)) {
					$this->collsfSimpleCMSSlots = sfSimpleCMSSlotPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastsfSimpleCMSSlotCriteria = $criteria;
		return $this->collsfSimpleCMSSlots;
	}

	/**
	 * Returns the number of related sfSimpleCMSSlot objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related sfSimpleCMSSlot objects.
	 * @throws     PropelException
	 */
	public function countsfSimpleCMSSlots(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfSimpleCMSPagePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collsfSimpleCMSSlots === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(sfSimpleCMSSlotPeer::PAGE_ID, $this->id);

				$count = sfSimpleCMSSlotPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(sfSimpleCMSSlotPeer::PAGE_ID, $this->id);

				if (!isset($this->lastsfSimpleCMSSlotCriteria) || !$this->lastsfSimpleCMSSlotCriteria->equals($criteria)) {
					$count = sfSimpleCMSSlotPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collsfSimpleCMSSlots);
				}
			} else {
				$count = count($this->collsfSimpleCMSSlots);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a sfSimpleCMSSlot object to this object
	 * through the sfSimpleCMSSlot foreign key attribute.
	 *
	 * @param      sfSimpleCMSSlot $l sfSimpleCMSSlot
	 * @return     void
	 * @throws     PropelException
	 */
	public function addsfSimpleCMSSlot(sfSimpleCMSSlot $l)
	{
		if ($this->collsfSimpleCMSSlots === null) {
			$this->initsfSimpleCMSSlots();
		}
		if (!in_array($l, $this->collsfSimpleCMSSlots, true)) { // only add it if the **same** object is not already associated
			array_push($this->collsfSimpleCMSSlots, $l);
			$l->setsfSimpleCMSPage($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collsfSimpleCMSPagesRelatedByTreeParent) {
				foreach ((array) $this->collsfSimpleCMSPagesRelatedByTreeParent as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collsfSimpleCMSSlots) {
				foreach ((array) $this->collsfSimpleCMSSlots as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collsfSimpleCMSPagesRelatedByTreeParent = null;
		$this->collsfSimpleCMSSlots = null;
			$this->asfSimpleCMSPageRelatedByTreeParent = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BasesfSimpleCMSPage:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BasesfSimpleCMSPage::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BasesfSimpleCMSPage
