default:
  stylesheets:    [main.css]
  javascripts:    [jquery-1.3.2.min.js, jquery.corners.min.js, resources.js, main.js, jGoogleAnalytics.js]
  
  
submitSuccess:
  stylesheets:    [main.css, smoothness/jquery-ui-1.7.1.custom.css]
  javascripts:    [jquery-1.3.2.min.js, jquery-ui-1.7.1.custom.min.js, jquery.corners.min.js, resources.js, main.js, jGoogleAnalytics.js]  
  
  