default:
  stylesheets:    [/sfSimpleCMSPlugin/css/CMSTemplates.css, main.css, print.css:{media: print}]
  javascripts:    [jquery-1.3.2.min.js, jquery.corners.min.js, main.js, jGoogleAnalytics.js, /js/tiny_mce/plugins/media/jscripts/embed.js]  
  has_layout:     on
  layout:         layout